baseURL = "http://cloudcite.net/blog/"
languageCode = "en-us"
title = "CloudCite Blog"
theme = "hugo-lamp"

[params]
    subtitle = "The Best Bibliography Generator Blog"
    author = "Hackdromeda Team"
    logo = "https://cloudcite.net/static/favicons/icon-150x150.png"
    description = "A Blog for CloudCite releases and feature improvements."
    paginate = 10

    # Publisher
    adsensePublisher = "ca-pub-2986930095691189"       # Required if you want to include Google Adsense
    adsenseSlot = "6966629535"                   # Required slot to display ads
    ## adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

    # SEO configs
    seotitle = "CloudCite Blog"
    ## googleSiteVerification = "google_site_verification_code"    # Google Webmaster
    ## msValidate = "bing_site_verification_code"                  # Bing Webmaster

    # Social networks
    email = "help@cloudcite.net"
    github = "Hackdromeda"
    twitter = "cloud_cite"
    linkedin = "cloudcite"
    facebook = "cloudcite"
    instagram = "cloudcite"
    youtube = "cloudcite"
    ## dribbble = "dribbble_username"

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.main]]
    name = "Releases"
    weight = 1
    identifier = "release"
    url = "/releases/"

[[menu.main]]
    name = "MLA Guide"
    weight = 1
    identifier = "mla"
    url = "/mla/"